### ISSUE TITLE
Parsing text files, return searching results

### ISSUE THREAD

**Issue by zequnyu** [zequnyu/cmdict#12]
`e2c file.txt` should return search result of words from the database.

**Comment by edxu96** [comment]
## Extract text from PDF files 

- [pdfminer/pdfminer.six](https://github.com/pdfminer/pdfminer.six)

**Comment by edxu96** [comment]
## Two Ways to Analyse Words

1. Extract highlighted unfamiliar words and present in a readable way. Different highlights can be distinguished by colours.
2. Extract other words in the PDF, assuming that the user is familiar with those. That way, the program knows the user's range.

**Comment by zequnyu** [comment]
@edxu96 did you try `GitHub/0xabu/pdfannots`? This is interesting one. For MIT license it means you can almost do anything with the source code. Just need to mention and honor the author.

**Comment by edxu96** [comment]
I tried. It is easy to use the method in terminal, but it may be hard to integrated into our code. There are 500 lines. For example, if we want to make a modification in order to return highlights based on colours, it may take several hours.

In contrast, though the functions in `PyMuPDF 1.17.3` are primitive (based on geometry), there are many examples and snippets. The author already solved the biggest problem for me with 10 lines of code. I read all the APIs yesterday, and I think it is a good package for parsing and writing PDF files.

**Comment by zequnyu** [comment]
Please also note the issue I mention here is we should support `.txt` words search, which is different from the `.PDF` highlights problem. So you should probably open a separate issue for the above discussion.
